name: Sync Content

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  workflow_dispatch: # Allow manual triggering

jobs:
  fetch-and-store-web-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install cheerio pg openai typescript ts-node @types/node @types/pg

      # Ensure you have the required directory structure
      - name: Create necessary directories
        run: mkdir -p scripts

      # Run the web content scraper script
      - name: Run web content scraper
        env:
          API_ENDPOINT: "https://open-source-content.xyz/v1/web"
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: "5432"
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PROCESS_LIMIT: ${{ secrets.PROCESS_LIMIT }}
        run: node scripts/fetch_web.ts
