name: Web Content Fetcher with Turso Database

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  workflow_dispatch: # Allow manual triggering

jobs:
  fetch-and-store-web-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 libsql-experimental

      # Run Web content fetcher script
      - name: Run Web content fetcher script
        env:
          API_ENDPOINT: "https://open-source-content.xyz/v1/web"
        run: python scripts/fetch_web.py

      # Upload database and results as artifacts (for backup)
      - name: Upload database
        uses: actions/upload-artifact@v4
        with:
          name: database-files
          path: |
            content.sqlite
            data/processed_weblinks.json
          retention-days: 5
